// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: master.proto

/*
	Package masterpb is a generated protocol buffer package.

	It is generated from these files:
		master.proto

	It has these top-level messages:
		Route
		GetRouteRequest
		GetRouteResponse
		PSRegisterRequest
		PSRegisterResponse
		PSConfig
		PSHeartbeatRequest
		PSHeartbeatResponse
		PartitionInfo
*/
package masterpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import meta "github.com/tiglabs/baud/proto/metapb"
import stats "."

import github_com_tiglabs_baud_proto_metapb "github.com/tiglabs/baud/proto/metapb"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Route struct {
	meta.Partition `protobuf:"bytes,1,opt,name=partition,embedded=partition" json:"partition"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptorMaster, []int{0} }

type GetRouteRequest struct {
	meta.RequestHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	Space              github_com_tiglabs_baud_proto_metapb.SpaceID `protobuf:"varint,2,opt,name=space,proto3,casttype=github.com/tiglabs/baud/proto/metapb.SpaceID" json:"space,omitempty"`
	Slot               github_com_tiglabs_baud_proto_metapb.SlotID  `protobuf:"varint,3,opt,name=slot,proto3,casttype=github.com/tiglabs/baud/proto/metapb.SlotID" json:"slot,omitempty"`
}

func (m *GetRouteRequest) Reset()                    { *m = GetRouteRequest{} }
func (*GetRouteRequest) ProtoMessage()               {}
func (*GetRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptorMaster, []int{1} }

type GetRouteResponse struct {
	meta.ResponseHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	Routes              []Route `protobuf:"bytes,2,rep,name=routes" json:"routes"`
}

func (m *GetRouteResponse) Reset()                    { *m = GetRouteResponse{} }
func (*GetRouteResponse) ProtoMessage()               {}
func (*GetRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptorMaster, []int{2} }

type PSRegisterRequest struct {
	meta.RequestHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	NodeID             github_com_tiglabs_baud_proto_metapb.NodeID `protobuf:"varint,2,opt,name=nodeID,proto3,casttype=github.com/tiglabs/baud/proto/metapb.NodeID" json:"nodeID,omitempty"`
	Ip                 string                                      `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	stats.RuntimeInfo  `protobuf:"bytes,4,opt,name=runtime_info,json=runtimeInfo,embedded=runtime_info" json:"runtime_info"`
}

func (m *PSRegisterRequest) Reset()                    { *m = PSRegisterRequest{} }
func (*PSRegisterRequest) ProtoMessage()               {}
func (*PSRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptorMaster, []int{3} }

type PSRegisterResponse struct {
	meta.ResponseHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	NodeID              github_com_tiglabs_baud_proto_metapb.NodeID `protobuf:"varint,2,opt,name=nodeID,proto3,casttype=github.com/tiglabs/baud/proto/metapb.NodeID" json:"nodeID,omitempty"`
	PSConfig            `protobuf:"bytes,3,opt,name=config,embedded=config" json:"config"`
	Partitions          []meta.Partition `protobuf:"bytes,4,rep,name=partitions" json:"partitions"`
}

func (m *PSRegisterResponse) Reset()                    { *m = PSRegisterResponse{} }
func (*PSRegisterResponse) ProtoMessage()               {}
func (*PSRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptorMaster, []int{4} }

type PSConfig struct {
	RPCPort                 int    `protobuf:"varint,1,opt,name=rpc_port,json=rpcPort,proto3,casttype=int" json:"rpc_port,omitempty"`
	AdminPort               int    `protobuf:"varint,2,opt,name=admin_port,json=adminPort,proto3,casttype=int" json:"admin_port,omitempty"`
	HeartbeatInterval       int    `protobuf:"varint,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3,casttype=int" json:"heartbeat_interval,omitempty"`
	RaftHeartbeatPort       int    `protobuf:"varint,4,opt,name=raft_heartbeat_port,json=raftHeartbeatPort,proto3,casttype=int" json:"raft_heartbeat_port,omitempty"`
	RaftReplicatePort       int    `protobuf:"varint,5,opt,name=raft_replicate_port,json=raftReplicatePort,proto3,casttype=int" json:"raft_replicate_port,omitempty"`
	RaftHeartbeatInterval   int    `protobuf:"varint,6,opt,name=raft_heartbeat_interval,json=raftHeartbeatInterval,proto3,casttype=int" json:"raft_heartbeat_interval,omitempty"`
	RaftRetainLogs          uint64 `protobuf:"varint,7,opt,name=raft_retain_logs,json=raftRetainLogs,proto3" json:"raft_retain_logs,omitempty"`
	RaftReplicaConcurrency  int    `protobuf:"varint,8,opt,name=raft_replica_concurrency,json=raftReplicaConcurrency,proto3,casttype=int" json:"raft_replica_concurrency,omitempty"`
	RaftSnapshotConcurrency int    `protobuf:"varint,9,opt,name=raft_snapshot_concurrency,json=raftSnapshotConcurrency,proto3,casttype=int" json:"raft_snapshot_concurrency,omitempty"`
}

func (m *PSConfig) Reset()                    { *m = PSConfig{} }
func (*PSConfig) ProtoMessage()               {}
func (*PSConfig) Descriptor() ([]byte, []int) { return fileDescriptorMaster, []int{5} }

type PSHeartbeatRequest struct {
	meta.RequestHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
	NodeID             github_com_tiglabs_baud_proto_metapb.NodeID `protobuf:"varint,2,opt,name=nodeID,proto3,casttype=github.com/tiglabs/baud/proto/metapb.NodeID" json:"nodeID,omitempty"`
	Partitions         []PartitionInfo                             `protobuf:"bytes,3,rep,name=partitions" json:"partitions"`
	SysStats           stats.NodeSysStats                          `protobuf:"bytes,4,opt,name=sys_stats,json=sysStats" json:"sys_stats"`
}

func (m *PSHeartbeatRequest) Reset()                    { *m = PSHeartbeatRequest{} }
func (*PSHeartbeatRequest) ProtoMessage()               {}
func (*PSHeartbeatRequest) Descriptor() ([]byte, []int) { return fileDescriptorMaster, []int{6} }

type PSHeartbeatResponse struct {
	meta.ResponseHeader `protobuf:"bytes,1,opt,name=header,embedded=header" json:"header"`
}

func (m *PSHeartbeatResponse) Reset()                    { *m = PSHeartbeatResponse{} }
func (*PSHeartbeatResponse) ProtoMessage()               {}
func (*PSHeartbeatResponse) Descriptor() ([]byte, []int) { return fileDescriptorMaster, []int{7} }

type PartitionInfo struct {
	ID         github_com_tiglabs_baud_proto_metapb.PartitionID `protobuf:"varint,1,opt,name=id,proto3,casttype=github.com/tiglabs/baud/proto/metapb.PartitionID" json:"id,omitempty"`
	IsLeader   bool                                             `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	Status     meta.PartitionStatus                             `protobuf:"varint,3,opt,name=status,proto3,enum=PartitionStatus" json:"status,omitempty"`
	Epoch      meta.PartitionEpoch                              `protobuf:"bytes,4,opt,name=epoch" json:"epoch"`
	RaftStatus *stats.RaftStatus                                `protobuf:"bytes,5,opt,name=raft_status,json=raftStatus" json:"raft_status,omitempty"`
	Statistics stats.PartitionStats                             `protobuf:"bytes,6,opt,name=statistics" json:"statistics"`
}

func (m *PartitionInfo) Reset()                    { *m = PartitionInfo{} }
func (*PartitionInfo) ProtoMessage()               {}
func (*PartitionInfo) Descriptor() ([]byte, []int) { return fileDescriptorMaster, []int{8} }

func init() {
	proto.RegisterType((*Route)(nil), "Route")
	proto.RegisterType((*GetRouteRequest)(nil), "GetRouteRequest")
	proto.RegisterType((*GetRouteResponse)(nil), "GetRouteResponse")
	proto.RegisterType((*PSRegisterRequest)(nil), "PSRegisterRequest")
	proto.RegisterType((*PSRegisterResponse)(nil), "PSRegisterResponse")
	proto.RegisterType((*PSConfig)(nil), "PSConfig")
	proto.RegisterType((*PSHeartbeatRequest)(nil), "PSHeartbeatRequest")
	proto.RegisterType((*PSHeartbeatResponse)(nil), "PSHeartbeatResponse")
	proto.RegisterType((*PartitionInfo)(nil), "PartitionInfo")
}
func (this *Route) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Route)
	if !ok {
		that2, ok := that.(Route)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Partition.Equal(&that1.Partition) {
		return false
	}
	return true
}
func (this *GetRouteRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetRouteRequest)
	if !ok {
		that2, ok := that.(GetRouteRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.RequestHeader.Equal(&that1.RequestHeader) {
		return false
	}
	if this.Space != that1.Space {
		return false
	}
	if this.Slot != that1.Slot {
		return false
	}
	return true
}
func (this *GetRouteResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetRouteResponse)
	if !ok {
		that2, ok := that.(GetRouteResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ResponseHeader.Equal(&that1.ResponseHeader) {
		return false
	}
	if len(this.Routes) != len(that1.Routes) {
		return false
	}
	for i := range this.Routes {
		if !this.Routes[i].Equal(&that1.Routes[i]) {
			return false
		}
	}
	return true
}
func (this *PSRegisterRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PSRegisterRequest)
	if !ok {
		that2, ok := that.(PSRegisterRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.RequestHeader.Equal(&that1.RequestHeader) {
		return false
	}
	if this.NodeID != that1.NodeID {
		return false
	}
	if this.Ip != that1.Ip {
		return false
	}
	if !this.RuntimeInfo.Equal(&that1.RuntimeInfo) {
		return false
	}
	return true
}
func (this *PSRegisterResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PSRegisterResponse)
	if !ok {
		that2, ok := that.(PSRegisterResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ResponseHeader.Equal(&that1.ResponseHeader) {
		return false
	}
	if this.NodeID != that1.NodeID {
		return false
	}
	if !this.PSConfig.Equal(&that1.PSConfig) {
		return false
	}
	if len(this.Partitions) != len(that1.Partitions) {
		return false
	}
	for i := range this.Partitions {
		if !this.Partitions[i].Equal(&that1.Partitions[i]) {
			return false
		}
	}
	return true
}
func (this *PSConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PSConfig)
	if !ok {
		that2, ok := that.(PSConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RPCPort != that1.RPCPort {
		return false
	}
	if this.AdminPort != that1.AdminPort {
		return false
	}
	if this.HeartbeatInterval != that1.HeartbeatInterval {
		return false
	}
	if this.RaftHeartbeatPort != that1.RaftHeartbeatPort {
		return false
	}
	if this.RaftReplicatePort != that1.RaftReplicatePort {
		return false
	}
	if this.RaftHeartbeatInterval != that1.RaftHeartbeatInterval {
		return false
	}
	if this.RaftRetainLogs != that1.RaftRetainLogs {
		return false
	}
	if this.RaftReplicaConcurrency != that1.RaftReplicaConcurrency {
		return false
	}
	if this.RaftSnapshotConcurrency != that1.RaftSnapshotConcurrency {
		return false
	}
	return true
}
func (this *PSHeartbeatRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PSHeartbeatRequest)
	if !ok {
		that2, ok := that.(PSHeartbeatRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.RequestHeader.Equal(&that1.RequestHeader) {
		return false
	}
	if this.NodeID != that1.NodeID {
		return false
	}
	if len(this.Partitions) != len(that1.Partitions) {
		return false
	}
	for i := range this.Partitions {
		if !this.Partitions[i].Equal(&that1.Partitions[i]) {
			return false
		}
	}
	if !this.SysStats.Equal(&that1.SysStats) {
		return false
	}
	return true
}
func (this *PSHeartbeatResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PSHeartbeatResponse)
	if !ok {
		that2, ok := that.(PSHeartbeatResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ResponseHeader.Equal(&that1.ResponseHeader) {
		return false
	}
	return true
}
func (this *PartitionInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PartitionInfo)
	if !ok {
		that2, ok := that.(PartitionInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	if this.IsLeader != that1.IsLeader {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if !this.Epoch.Equal(&that1.Epoch) {
		return false
	}
	if !this.RaftStatus.Equal(that1.RaftStatus) {
		return false
	}
	if !this.Statistics.Equal(&that1.Statistics) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MasterRpc service

type MasterRpcClient interface {
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error)
	PSRegister(ctx context.Context, in *PSRegisterRequest, opts ...grpc.CallOption) (*PSRegisterResponse, error)
	PSHeartbeat(ctx context.Context, in *PSHeartbeatRequest, opts ...grpc.CallOption) (*PSHeartbeatResponse, error)
}

type masterRpcClient struct {
	cc *grpc.ClientConn
}

func NewMasterRpcClient(cc *grpc.ClientConn) MasterRpcClient {
	return &masterRpcClient{cc}
}

func (c *masterRpcClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error) {
	out := new(GetRouteResponse)
	err := grpc.Invoke(ctx, "/MasterRpc/GetRoute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterRpcClient) PSRegister(ctx context.Context, in *PSRegisterRequest, opts ...grpc.CallOption) (*PSRegisterResponse, error) {
	out := new(PSRegisterResponse)
	err := grpc.Invoke(ctx, "/MasterRpc/PSRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterRpcClient) PSHeartbeat(ctx context.Context, in *PSHeartbeatRequest, opts ...grpc.CallOption) (*PSHeartbeatResponse, error) {
	out := new(PSHeartbeatResponse)
	err := grpc.Invoke(ctx, "/MasterRpc/PSHeartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MasterRpc service

type MasterRpcServer interface {
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error)
	PSRegister(context.Context, *PSRegisterRequest) (*PSRegisterResponse, error)
	PSHeartbeat(context.Context, *PSHeartbeatRequest) (*PSHeartbeatResponse, error)
}

func RegisterMasterRpcServer(s *grpc.Server, srv MasterRpcServer) {
	s.RegisterService(&_MasterRpc_serviceDesc, srv)
}

func _MasterRpc_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterRpcServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MasterRpc/GetRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterRpcServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterRpc_PSRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PSRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterRpcServer).PSRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MasterRpc/PSRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterRpcServer).PSRegister(ctx, req.(*PSRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterRpc_PSHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PSHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterRpcServer).PSHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MasterRpc/PSHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterRpcServer).PSHeartbeat(ctx, req.(*PSHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MasterRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MasterRpc",
	HandlerType: (*MasterRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoute",
			Handler:    _MasterRpc_GetRoute_Handler,
		},
		{
			MethodName: "PSRegister",
			Handler:    _MasterRpc_PSRegister_Handler,
		},
		{
			MethodName: "PSHeartbeat",
			Handler:    _MasterRpc_PSHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}

func (m *Route) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Route) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.Partition.Size()))
	n1, err := m.Partition.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	return i, nil
}

func (m *GetRouteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRouteRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.RequestHeader.Size()))
	n2, err := m.RequestHeader.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if m.Space != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.Space))
	}
	if m.Slot != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.Slot))
	}
	return i, nil
}

func (m *GetRouteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRouteResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.ResponseHeader.Size()))
	n3, err := m.ResponseHeader.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	if len(m.Routes) > 0 {
		for _, msg := range m.Routes {
			dAtA[i] = 0x12
			i++
			i = encodeVarintMaster(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *PSRegisterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PSRegisterRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.RequestHeader.Size()))
	n4, err := m.RequestHeader.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	if m.NodeID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.NodeID))
	}
	if len(m.Ip) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMaster(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	dAtA[i] = 0x22
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.RuntimeInfo.Size()))
	n5, err := m.RuntimeInfo.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n5
	return i, nil
}

func (m *PSRegisterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PSRegisterResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.ResponseHeader.Size()))
	n6, err := m.ResponseHeader.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n6
	if m.NodeID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.NodeID))
	}
	dAtA[i] = 0x1a
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.PSConfig.Size()))
	n7, err := m.PSConfig.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n7
	if len(m.Partitions) > 0 {
		for _, msg := range m.Partitions {
			dAtA[i] = 0x22
			i++
			i = encodeVarintMaster(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *PSConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PSConfig) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RPCPort != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.RPCPort))
	}
	if m.AdminPort != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.AdminPort))
	}
	if m.HeartbeatInterval != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.HeartbeatInterval))
	}
	if m.RaftHeartbeatPort != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.RaftHeartbeatPort))
	}
	if m.RaftReplicatePort != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.RaftReplicatePort))
	}
	if m.RaftHeartbeatInterval != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.RaftHeartbeatInterval))
	}
	if m.RaftRetainLogs != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.RaftRetainLogs))
	}
	if m.RaftReplicaConcurrency != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.RaftReplicaConcurrency))
	}
	if m.RaftSnapshotConcurrency != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.RaftSnapshotConcurrency))
	}
	return i, nil
}

func (m *PSHeartbeatRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PSHeartbeatRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.RequestHeader.Size()))
	n8, err := m.RequestHeader.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n8
	if m.NodeID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.NodeID))
	}
	if len(m.Partitions) > 0 {
		for _, msg := range m.Partitions {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintMaster(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x22
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.SysStats.Size()))
	n9, err := m.SysStats.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n9
	return i, nil
}

func (m *PSHeartbeatResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PSHeartbeatResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.ResponseHeader.Size()))
	n10, err := m.ResponseHeader.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n10
	return i, nil
}

func (m *PartitionInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PartitionInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.ID))
	}
	if m.IsLeader {
		dAtA[i] = 0x10
		i++
		if m.IsLeader {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Status != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.Status))
	}
	dAtA[i] = 0x22
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.Epoch.Size()))
	n11, err := m.Epoch.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n11
	if m.RaftStatus != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMaster(dAtA, i, uint64(m.RaftStatus.Size()))
		n12, err := m.RaftStatus.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n12
	}
	dAtA[i] = 0x32
	i++
	i = encodeVarintMaster(dAtA, i, uint64(m.Statistics.Size()))
	n13, err := m.Statistics.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n13
	return i, nil
}

func encodeVarintMaster(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedRoute(r randyMaster, easy bool) *Route {
	this := &Route{}
	v1 := meta.NewPopulatedPartition(r, easy)
	this.Partition = *v1
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetRouteRequest(r randyMaster, easy bool) *GetRouteRequest {
	this := &GetRouteRequest{}
	v2 := meta.NewPopulatedRequestHeader(r, easy)
	this.RequestHeader = *v2
	this.Space = github_com_tiglabs_baud_proto_metapb.SpaceID(r.Uint32())
	this.Slot = github_com_tiglabs_baud_proto_metapb.SlotID(r.Uint32())
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetRouteResponse(r randyMaster, easy bool) *GetRouteResponse {
	this := &GetRouteResponse{}
	v3 := meta.NewPopulatedResponseHeader(r, easy)
	this.ResponseHeader = *v3
	if r.Intn(10) != 0 {
		v4 := r.Intn(5)
		this.Routes = make([]Route, v4)
		for i := 0; i < v4; i++ {
			v5 := NewPopulatedRoute(r, easy)
			this.Routes[i] = *v5
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPSRegisterRequest(r randyMaster, easy bool) *PSRegisterRequest {
	this := &PSRegisterRequest{}
	v6 := meta.NewPopulatedRequestHeader(r, easy)
	this.RequestHeader = *v6
	this.NodeID = github_com_tiglabs_baud_proto_metapb.NodeID(r.Uint32())
	this.Ip = string(randStringMaster(r))
	v7 := stats.NewPopulatedRuntimeInfo(r, easy)
	this.RuntimeInfo = *v7
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPSRegisterResponse(r randyMaster, easy bool) *PSRegisterResponse {
	this := &PSRegisterResponse{}
	v8 := meta.NewPopulatedResponseHeader(r, easy)
	this.ResponseHeader = *v8
	this.NodeID = github_com_tiglabs_baud_proto_metapb.NodeID(r.Uint32())
	v9 := NewPopulatedPSConfig(r, easy)
	this.PSConfig = *v9
	if r.Intn(10) != 0 {
		v10 := r.Intn(5)
		this.Partitions = make([]meta.Partition, v10)
		for i := 0; i < v10; i++ {
			v11 := meta.NewPopulatedPartition(r, easy)
			this.Partitions[i] = *v11
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPSConfig(r randyMaster, easy bool) *PSConfig {
	this := &PSConfig{}
	this.RPCPort = int(r.Uint32())
	this.AdminPort = int(r.Uint32())
	this.HeartbeatInterval = int(r.Uint32())
	this.RaftHeartbeatPort = int(r.Uint32())
	this.RaftReplicatePort = int(r.Uint32())
	this.RaftHeartbeatInterval = int(r.Uint32())
	this.RaftRetainLogs = uint64(uint64(r.Uint32()))
	this.RaftReplicaConcurrency = int(r.Uint32())
	this.RaftSnapshotConcurrency = int(r.Uint32())
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPSHeartbeatRequest(r randyMaster, easy bool) *PSHeartbeatRequest {
	this := &PSHeartbeatRequest{}
	v12 := meta.NewPopulatedRequestHeader(r, easy)
	this.RequestHeader = *v12
	this.NodeID = github_com_tiglabs_baud_proto_metapb.NodeID(r.Uint32())
	if r.Intn(10) != 0 {
		v13 := r.Intn(5)
		this.Partitions = make([]PartitionInfo, v13)
		for i := 0; i < v13; i++ {
			v14 := NewPopulatedPartitionInfo(r, easy)
			this.Partitions[i] = *v14
		}
	}
	v15 := stats.NewPopulatedNodeSysStats(r, easy)
	this.SysStats = *v15
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPSHeartbeatResponse(r randyMaster, easy bool) *PSHeartbeatResponse {
	this := &PSHeartbeatResponse{}
	v16 := meta.NewPopulatedResponseHeader(r, easy)
	this.ResponseHeader = *v16
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPartitionInfo(r randyMaster, easy bool) *PartitionInfo {
	this := &PartitionInfo{}
	this.ID = github_com_tiglabs_baud_proto_metapb.PartitionID(r.Uint32())
	this.IsLeader = bool(bool(r.Intn(2) == 0))
	this.Status = meta.PartitionStatus([]int32{0, 1, 2, 3, 4}[r.Intn(5)])
	v17 := meta.NewPopulatedPartitionEpoch(r, easy)
	this.Epoch = *v17
	if r.Intn(10) != 0 {
		this.RaftStatus = stats.NewPopulatedRaftStatus(r, easy)
	}
	v18 := stats.NewPopulatedPartitionStats(r, easy)
	this.Statistics = *v18
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyMaster interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneMaster(r randyMaster) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringMaster(r randyMaster) string {
	v19 := r.Intn(100)
	tmps := make([]rune, v19)
	for i := 0; i < v19; i++ {
		tmps[i] = randUTF8RuneMaster(r)
	}
	return string(tmps)
}
func randUnrecognizedMaster(r randyMaster, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldMaster(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldMaster(dAtA []byte, r randyMaster, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateMaster(dAtA, uint64(key))
		v20 := r.Int63()
		if r.Intn(2) == 0 {
			v20 *= -1
		}
		dAtA = encodeVarintPopulateMaster(dAtA, uint64(v20))
	case 1:
		dAtA = encodeVarintPopulateMaster(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateMaster(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateMaster(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateMaster(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateMaster(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Route) Size() (n int) {
	var l int
	_ = l
	l = m.Partition.Size()
	n += 1 + l + sovMaster(uint64(l))
	return n
}

func (m *GetRouteRequest) Size() (n int) {
	var l int
	_ = l
	l = m.RequestHeader.Size()
	n += 1 + l + sovMaster(uint64(l))
	if m.Space != 0 {
		n += 1 + sovMaster(uint64(m.Space))
	}
	if m.Slot != 0 {
		n += 1 + sovMaster(uint64(m.Slot))
	}
	return n
}

func (m *GetRouteResponse) Size() (n int) {
	var l int
	_ = l
	l = m.ResponseHeader.Size()
	n += 1 + l + sovMaster(uint64(l))
	if len(m.Routes) > 0 {
		for _, e := range m.Routes {
			l = e.Size()
			n += 1 + l + sovMaster(uint64(l))
		}
	}
	return n
}

func (m *PSRegisterRequest) Size() (n int) {
	var l int
	_ = l
	l = m.RequestHeader.Size()
	n += 1 + l + sovMaster(uint64(l))
	if m.NodeID != 0 {
		n += 1 + sovMaster(uint64(m.NodeID))
	}
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovMaster(uint64(l))
	}
	l = m.RuntimeInfo.Size()
	n += 1 + l + sovMaster(uint64(l))
	return n
}

func (m *PSRegisterResponse) Size() (n int) {
	var l int
	_ = l
	l = m.ResponseHeader.Size()
	n += 1 + l + sovMaster(uint64(l))
	if m.NodeID != 0 {
		n += 1 + sovMaster(uint64(m.NodeID))
	}
	l = m.PSConfig.Size()
	n += 1 + l + sovMaster(uint64(l))
	if len(m.Partitions) > 0 {
		for _, e := range m.Partitions {
			l = e.Size()
			n += 1 + l + sovMaster(uint64(l))
		}
	}
	return n
}

func (m *PSConfig) Size() (n int) {
	var l int
	_ = l
	if m.RPCPort != 0 {
		n += 1 + sovMaster(uint64(m.RPCPort))
	}
	if m.AdminPort != 0 {
		n += 1 + sovMaster(uint64(m.AdminPort))
	}
	if m.HeartbeatInterval != 0 {
		n += 1 + sovMaster(uint64(m.HeartbeatInterval))
	}
	if m.RaftHeartbeatPort != 0 {
		n += 1 + sovMaster(uint64(m.RaftHeartbeatPort))
	}
	if m.RaftReplicatePort != 0 {
		n += 1 + sovMaster(uint64(m.RaftReplicatePort))
	}
	if m.RaftHeartbeatInterval != 0 {
		n += 1 + sovMaster(uint64(m.RaftHeartbeatInterval))
	}
	if m.RaftRetainLogs != 0 {
		n += 1 + sovMaster(uint64(m.RaftRetainLogs))
	}
	if m.RaftReplicaConcurrency != 0 {
		n += 1 + sovMaster(uint64(m.RaftReplicaConcurrency))
	}
	if m.RaftSnapshotConcurrency != 0 {
		n += 1 + sovMaster(uint64(m.RaftSnapshotConcurrency))
	}
	return n
}

func (m *PSHeartbeatRequest) Size() (n int) {
	var l int
	_ = l
	l = m.RequestHeader.Size()
	n += 1 + l + sovMaster(uint64(l))
	if m.NodeID != 0 {
		n += 1 + sovMaster(uint64(m.NodeID))
	}
	if len(m.Partitions) > 0 {
		for _, e := range m.Partitions {
			l = e.Size()
			n += 1 + l + sovMaster(uint64(l))
		}
	}
	l = m.SysStats.Size()
	n += 1 + l + sovMaster(uint64(l))
	return n
}

func (m *PSHeartbeatResponse) Size() (n int) {
	var l int
	_ = l
	l = m.ResponseHeader.Size()
	n += 1 + l + sovMaster(uint64(l))
	return n
}

func (m *PartitionInfo) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovMaster(uint64(m.ID))
	}
	if m.IsLeader {
		n += 2
	}
	if m.Status != 0 {
		n += 1 + sovMaster(uint64(m.Status))
	}
	l = m.Epoch.Size()
	n += 1 + l + sovMaster(uint64(l))
	if m.RaftStatus != nil {
		l = m.RaftStatus.Size()
		n += 1 + l + sovMaster(uint64(l))
	}
	l = m.Statistics.Size()
	n += 1 + l + sovMaster(uint64(l))
	return n
}

func sovMaster(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMaster(x uint64) (n int) {
	return sovMaster(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Route) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Route{`,
		`Partition:` + strings.Replace(strings.Replace(this.Partition.String(), "Partition", "meta.Partition", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetRouteRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetRouteRequest{`,
		`RequestHeader:` + strings.Replace(strings.Replace(this.RequestHeader.String(), "RequestHeader", "meta.RequestHeader", 1), `&`, ``, 1) + `,`,
		`Space:` + fmt.Sprintf("%v", this.Space) + `,`,
		`Slot:` + fmt.Sprintf("%v", this.Slot) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetRouteResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetRouteResponse{`,
		`ResponseHeader:` + strings.Replace(strings.Replace(this.ResponseHeader.String(), "ResponseHeader", "meta.ResponseHeader", 1), `&`, ``, 1) + `,`,
		`Routes:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Routes), "Route", "Route", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PSRegisterRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PSRegisterRequest{`,
		`RequestHeader:` + strings.Replace(strings.Replace(this.RequestHeader.String(), "RequestHeader", "meta.RequestHeader", 1), `&`, ``, 1) + `,`,
		`NodeID:` + fmt.Sprintf("%v", this.NodeID) + `,`,
		`Ip:` + fmt.Sprintf("%v", this.Ip) + `,`,
		`RuntimeInfo:` + strings.Replace(strings.Replace(this.RuntimeInfo.String(), "RuntimeInfo", "stats.RuntimeInfo", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PSRegisterResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PSRegisterResponse{`,
		`ResponseHeader:` + strings.Replace(strings.Replace(this.ResponseHeader.String(), "ResponseHeader", "meta.ResponseHeader", 1), `&`, ``, 1) + `,`,
		`NodeID:` + fmt.Sprintf("%v", this.NodeID) + `,`,
		`PSConfig:` + strings.Replace(strings.Replace(this.PSConfig.String(), "PSConfig", "PSConfig", 1), `&`, ``, 1) + `,`,
		`Partitions:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Partitions), "Partition", "meta.Partition", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PSConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PSConfig{`,
		`RPCPort:` + fmt.Sprintf("%v", this.RPCPort) + `,`,
		`AdminPort:` + fmt.Sprintf("%v", this.AdminPort) + `,`,
		`HeartbeatInterval:` + fmt.Sprintf("%v", this.HeartbeatInterval) + `,`,
		`RaftHeartbeatPort:` + fmt.Sprintf("%v", this.RaftHeartbeatPort) + `,`,
		`RaftReplicatePort:` + fmt.Sprintf("%v", this.RaftReplicatePort) + `,`,
		`RaftHeartbeatInterval:` + fmt.Sprintf("%v", this.RaftHeartbeatInterval) + `,`,
		`RaftRetainLogs:` + fmt.Sprintf("%v", this.RaftRetainLogs) + `,`,
		`RaftReplicaConcurrency:` + fmt.Sprintf("%v", this.RaftReplicaConcurrency) + `,`,
		`RaftSnapshotConcurrency:` + fmt.Sprintf("%v", this.RaftSnapshotConcurrency) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PSHeartbeatRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PSHeartbeatRequest{`,
		`RequestHeader:` + strings.Replace(strings.Replace(this.RequestHeader.String(), "RequestHeader", "meta.RequestHeader", 1), `&`, ``, 1) + `,`,
		`NodeID:` + fmt.Sprintf("%v", this.NodeID) + `,`,
		`Partitions:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Partitions), "PartitionInfo", "PartitionInfo", 1), `&`, ``, 1) + `,`,
		`SysStats:` + strings.Replace(strings.Replace(this.SysStats.String(), "NodeSysStats", "stats.NodeSysStats", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PSHeartbeatResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PSHeartbeatResponse{`,
		`ResponseHeader:` + strings.Replace(strings.Replace(this.ResponseHeader.String(), "ResponseHeader", "meta.ResponseHeader", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PartitionInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PartitionInfo{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`IsLeader:` + fmt.Sprintf("%v", this.IsLeader) + `,`,
		`Status:` + fmt.Sprintf("%v", this.Status) + `,`,
		`Epoch:` + strings.Replace(strings.Replace(this.Epoch.String(), "PartitionEpoch", "meta.PartitionEpoch", 1), `&`, ``, 1) + `,`,
		`RaftStatus:` + strings.Replace(fmt.Sprintf("%v", this.RaftStatus), "RaftStatus", "stats.RaftStatus", 1) + `,`,
		`Statistics:` + strings.Replace(strings.Replace(this.Statistics.String(), "PartitionStats", "stats.PartitionStats", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMaster(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Route) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Route: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Route: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Partition", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Partition.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRouteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRouteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRouteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RequestHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Space", wireType)
			}
			m.Space = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Space |= (github_com_tiglabs_baud_proto_metapb.SpaceID(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= (github_com_tiglabs_baud_proto_metapb.SlotID(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRouteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRouteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRouteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ResponseHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Routes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Routes = append(m.Routes, Route{})
			if err := m.Routes[len(m.Routes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PSRegisterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PSRegisterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PSRegisterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RequestHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= (github_com_tiglabs_baud_proto_metapb.NodeID(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuntimeInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RuntimeInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PSRegisterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PSRegisterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PSRegisterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ResponseHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= (github_com_tiglabs_baud_proto_metapb.NodeID(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PSConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PSConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Partitions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Partitions = append(m.Partitions, meta.Partition{})
			if err := m.Partitions[len(m.Partitions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PSConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PSConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PSConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RPCPort", wireType)
			}
			m.RPCPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RPCPort |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdminPort", wireType)
			}
			m.AdminPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AdminPort |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeartbeatInterval", wireType)
			}
			m.HeartbeatInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HeartbeatInterval |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftHeartbeatPort", wireType)
			}
			m.RaftHeartbeatPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftHeartbeatPort |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftReplicatePort", wireType)
			}
			m.RaftReplicatePort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftReplicatePort |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftHeartbeatInterval", wireType)
			}
			m.RaftHeartbeatInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftHeartbeatInterval |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftRetainLogs", wireType)
			}
			m.RaftRetainLogs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftRetainLogs |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftReplicaConcurrency", wireType)
			}
			m.RaftReplicaConcurrency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftReplicaConcurrency |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftSnapshotConcurrency", wireType)
			}
			m.RaftSnapshotConcurrency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftSnapshotConcurrency |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PSHeartbeatRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PSHeartbeatRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PSHeartbeatRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RequestHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= (github_com_tiglabs_baud_proto_metapb.NodeID(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Partitions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Partitions = append(m.Partitions, PartitionInfo{})
			if err := m.Partitions[len(m.Partitions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SysStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SysStats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PSHeartbeatResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PSHeartbeatResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PSHeartbeatResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ResponseHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PartitionInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PartitionInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PartitionInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (github_com_tiglabs_baud_proto_metapb.PartitionID(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsLeader", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsLeader = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (meta.PartitionStatus(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Epoch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RaftStatus == nil {
				m.RaftStatus = &stats.RaftStatus{}
			}
			if err := m.RaftStatus.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Statistics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Statistics.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMaster(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMaster
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMaster
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMaster(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMaster = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMaster   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("master.proto", fileDescriptorMaster) }

var fileDescriptorMaster = []byte{
	// 968 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xb7, 0xd3, 0x24, 0x4d, 0x5e, 0xda, 0xb4, 0x9d, 0xf2, 0x27, 0x14, 0xc9, 0xa9, 0x2c, 0x84,
	0x22, 0x75, 0xd7, 0xe9, 0x86, 0x3f, 0xd5, 0x2e, 0x07, 0x20, 0x2d, 0xa2, 0x81, 0x05, 0xc2, 0xe4,
	0xc6, 0x25, 0x72, 0x9c, 0x49, 0x32, 0x22, 0xf1, 0x18, 0xcf, 0x04, 0xa9, 0x37, 0xf8, 0x06, 0x7c,
	0x0c, 0xee, 0x70, 0xe0, 0xc8, 0xb1, 0xc7, 0x3d, 0x72, 0x8a, 0x36, 0xde, 0x2f, 0xc0, 0x11, 0xf6,
	0x80, 0x90, 0x9f, 0x9d, 0xd8, 0x4e, 0x17, 0xa9, 0xaa, 0x84, 0xb4, 0xa7, 0x64, 0xde, 0xfc, 0xde,
	0xef, 0xbd, 0xf7, 0x9b, 0xf7, 0x66, 0x0c, 0x3b, 0x33, 0x5b, 0x2a, 0xe6, 0x5b, 0x9e, 0x2f, 0x94,
	0x38, 0xba, 0x3f, 0xe6, 0x6a, 0x32, 0x1f, 0x58, 0x8e, 0x98, 0x35, 0xc7, 0x62, 0x2c, 0x9a, 0x68,
	0x1e, 0xcc, 0x47, 0xb8, 0xc2, 0x05, 0xfe, 0x8b, 0xe1, 0xcd, 0x14, 0x5c, 0xf1, 0xf1, 0xd4, 0x1e,
	0xc8, 0xe6, 0xc0, 0x9e, 0x0f, 0x23, 0xb7, 0xe6, 0x8c, 0x29, 0xdb, 0x1b, 0xe0, 0x4f, 0xec, 0x50,
	0x91, 0xca, 0x56, 0x32, 0x5a, 0x98, 0x1f, 0x40, 0x81, 0x8a, 0xb9, 0x62, 0xa4, 0x05, 0x65, 0xcf,
	0xf6, 0x15, 0x57, 0x5c, 0xb8, 0x35, 0xfd, 0x58, 0x6f, 0x54, 0x5a, 0x60, 0x75, 0x57, 0x96, 0x76,
	0xe9, 0x7a, 0x51, 0xd7, 0x9e, 0x2c, 0xea, 0x3a, 0x4d, 0x60, 0xe6, 0x52, 0x87, 0xbd, 0x4f, 0x99,
	0x42, 0x02, 0xca, 0xbe, 0x9b, 0x33, 0xa9, 0xc8, 0x29, 0x14, 0x27, 0xcc, 0x1e, 0x32, 0x3f, 0x26,
	0xa9, 0x5a, 0xf1, 0xce, 0x25, 0x5a, 0x53, 0x44, 0x31, 0x8e, 0x7c, 0x05, 0x05, 0xe9, 0xd9, 0x0e,
	0xab, 0xe5, 0x8e, 0xf5, 0xc6, 0x6e, 0xfb, 0x61, 0xb0, 0xa8, 0x17, 0x7a, 0xa1, 0xe1, 0xf9, 0xa2,
	0x7e, 0xef, 0x36, 0xc5, 0x59, 0x88, 0xee, 0x5c, 0xd0, 0x88, 0x87, 0x7c, 0x0e, 0x79, 0x39, 0x15,
	0xaa, 0xb6, 0x85, 0x7c, 0x67, 0xc1, 0xa2, 0x9e, 0xef, 0x4d, 0x85, 0x7a, 0xbe, 0xa8, 0x9f, 0xdc,
	0x8e, 0x6e, 0x2a, 0x54, 0xe7, 0x82, 0x22, 0x89, 0xf9, 0x2d, 0xec, 0x27, 0x25, 0x4a, 0x4f, 0xb8,
	0x92, 0x91, 0x07, 0x1b, 0x35, 0xee, 0x59, 0xab, 0xad, 0xff, 0x2c, 0xf2, 0x2d, 0x28, 0xfa, 0x21,
	0x87, 0xac, 0xe5, 0x8e, 0xb7, 0x1a, 0x95, 0x56, 0xd1, 0x42, 0xca, 0x76, 0x3e, 0x44, 0xd2, 0x78,
	0xcf, 0x7c, 0xa6, 0xc3, 0x41, 0xb7, 0x47, 0xd9, 0x98, 0x87, 0xfd, 0x70, 0x77, 0x49, 0xbf, 0x86,
	0xa2, 0x2b, 0x86, 0xac, 0x73, 0x91, 0xd2, 0xb4, 0xf8, 0x25, 0x5a, 0x6e, 0xad, 0x42, 0x04, 0xa7,
	0x31, 0x11, 0xa9, 0x42, 0x8e, 0x7b, 0x28, 0x69, 0x99, 0xe6, 0xb8, 0x47, 0x1e, 0xc2, 0x8e, 0x3f,
	0x77, 0x15, 0x9f, 0xb1, 0x3e, 0x77, 0x47, 0xa2, 0x96, 0xc7, 0xd4, 0x76, 0x2c, 0x1a, 0x19, 0x3b,
	0xee, 0x48, 0xa4, 0x12, 0xab, 0xf8, 0x89, 0xd9, 0xfc, 0x5b, 0x07, 0x92, 0xae, 0xf2, 0xee, 0xaa,
	0xfe, 0x0f, 0x75, 0x9e, 0x40, 0xd1, 0x11, 0xee, 0x88, 0x8f, 0xb1, 0xd6, 0x4a, 0xab, 0x6c, 0x75,
	0x7b, 0xe7, 0x68, 0x48, 0xc7, 0x8f, 0x20, 0xe4, 0x14, 0x60, 0x3d, 0x0d, 0xb2, 0x96, 0xc7, 0x93,
	0x4d, 0x4f, 0x4d, 0x74, 0xba, 0x29, 0x8c, 0xf9, 0xcf, 0x16, 0x94, 0x56, 0x84, 0xe4, 0x3e, 0x94,
	0x7c, 0xcf, 0xe9, 0x7b, 0xc2, 0x57, 0x58, 0xf3, 0x6e, 0x9b, 0x04, 0x8b, 0xfa, 0x36, 0xed, 0x9e,
	0x77, 0x85, 0x1f, 0xf6, 0xeb, 0x16, 0x77, 0x15, 0xdd, 0xf6, 0x3d, 0x27, 0x5c, 0x93, 0xb7, 0x01,
	0xec, 0xe1, 0x8c, 0xbb, 0x91, 0x43, 0x54, 0xf1, 0xf6, 0x0a, 0x55, 0xc6, 0x2d, 0xc4, 0xbd, 0x0f,
	0x64, 0xc2, 0x6c, 0x5f, 0x0d, 0x98, 0xad, 0xfa, 0xdc, 0x55, 0xcc, 0xff, 0xde, 0x9e, 0xc6, 0xd3,
	0xb0, 0xc6, 0x1f, 0xac, 0x21, 0x9d, 0x18, 0x41, 0xce, 0xe0, 0xd0, 0xb7, 0x47, 0xaa, 0x9f, 0x38,
	0x63, 0xa0, 0xfc, 0x86, 0x63, 0x88, 0xb9, 0x5c, 0x41, 0x30, 0xe0, 0xca, 0xd1, 0x67, 0xde, 0x94,
	0x3b, 0xb6, 0x62, 0x91, 0x63, 0xe1, 0x05, 0x8e, 0x74, 0x05, 0x41, 0xc7, 0x0f, 0xe1, 0xf5, 0x8d,
	0x88, 0xeb, 0x74, 0x8b, 0x59, 0xe7, 0x57, 0x33, 0x51, 0xd7, 0x29, 0x37, 0x60, 0x3f, 0x8e, 0xac,
	0x6c, 0xee, 0xf6, 0xa7, 0x62, 0x2c, 0x6b, 0xdb, 0xc7, 0x7a, 0x23, 0x4f, 0xab, 0x51, 0xb4, 0xd0,
	0xfc, 0x58, 0x8c, 0x25, 0xf9, 0x18, 0x6a, 0xe9, 0x1c, 0xfb, 0x8e, 0x70, 0x9d, 0xb9, 0xef, 0x33,
	0xd7, 0xb9, 0xaa, 0x95, 0xb2, 0xb1, 0x5e, 0x4b, 0x25, 0x7a, 0x9e, 0xc0, 0xc8, 0x39, 0xbc, 0x81,
	0x14, 0xd2, 0xb5, 0x3d, 0x39, 0x11, 0x2a, 0xc3, 0x51, 0xce, 0x72, 0x60, 0x5d, 0xbd, 0x18, 0x98,
	0x22, 0x31, 0x7f, 0xcc, 0x85, 0xcd, 0xbf, 0xae, 0xe4, 0xa5, 0x9a, 0xf1, 0x77, 0x33, 0xed, 0xbc,
	0x85, 0xed, 0x5c, 0x4d, 0xda, 0x19, 0x67, 0xfa, 0x46, 0x4b, 0x93, 0x53, 0x28, 0xcb, 0x2b, 0xd9,
	0xc7, 0x57, 0x25, 0xbe, 0x06, 0x76, 0x91, 0xb9, 0x77, 0x25, 0x7b, 0xa1, 0x31, 0xf6, 0x29, 0xc9,
	0x78, 0x6d, 0x5e, 0xc2, 0x61, 0x46, 0x82, 0x3b, 0x5f, 0x00, 0xe6, 0xaf, 0x39, 0xd8, 0xcd, 0xe4,
	0x47, 0x3e, 0x83, 0x1c, 0x1f, 0xc6, 0xd3, 0xf4, 0x28, 0x58, 0xd4, 0x73, 0x28, 0xc7, 0xe9, 0xad,
	0xe4, 0x48, 0x98, 0x2e, 0x68, 0x8e, 0x0f, 0xc9, 0x9b, 0x50, 0xe6, 0xb2, 0x3f, 0x8d, 0x72, 0x0a,
	0x55, 0x2e, 0xd1, 0x12, 0x97, 0x8f, 0x23, 0xfd, 0x1b, 0x50, 0x0c, 0x4b, 0x9e, 0x4b, 0x9c, 0xac,
	0x6a, 0x6b, 0x3f, 0x71, 0xef, 0xa1, 0x9d, 0xc6, 0xfb, 0xe4, 0x04, 0x0a, 0xcc, 0x13, 0xce, 0x24,
	0x16, 0x67, 0x2f, 0x01, 0x7e, 0x12, 0x9a, 0x63, 0x79, 0x22, 0x0c, 0xb9, 0x07, 0x95, 0xa8, 0xc9,
	0x22, 0xee, 0x02, 0xba, 0x54, 0x2c, 0x1a, 0xb6, 0x53, 0x44, 0x0b, 0xfe, 0xfa, 0x3f, 0x79, 0x0f,
	0x20, 0x04, 0x72, 0xa9, 0xb8, 0x23, 0x71, 0x66, 0x32, 0xfc, 0x69, 0xf9, 0x53, 0xc0, 0xd6, 0x2f,
	0x3a, 0x94, 0xbf, 0xc0, 0x6f, 0x0e, 0xea, 0x39, 0xe4, 0x01, 0x94, 0x56, 0x4f, 0x1c, 0xd9, 0xb7,
	0x36, 0x1e, 0xf4, 0xa3, 0x03, 0x6b, 0xf3, 0xfd, 0x33, 0x35, 0x72, 0x06, 0x90, 0xdc, 0xe0, 0x84,
	0x58, 0x37, 0x1e, 0xad, 0xa3, 0x43, 0xeb, 0xe6, 0x15, 0x6f, 0x6a, 0xe4, 0x11, 0x54, 0x52, 0x47,
	0x4f, 0x42, 0xd4, 0xe6, 0x2c, 0x1c, 0xbd, 0x62, 0xbd, 0xa0, 0x3b, 0x4c, 0xad, 0xfd, 0xd1, 0xf5,
	0xd2, 0xd0, 0xfe, 0x58, 0x1a, 0xda, 0xd3, 0xa5, 0xa1, 0xfd, 0xb9, 0x34, 0xb4, 0xbf, 0x96, 0x86,
	0xfe, 0x43, 0x60, 0xe8, 0x3f, 0x07, 0x86, 0xfe, 0x5b, 0x60, 0x68, 0xbf, 0x07, 0x86, 0x76, 0x1d,
	0x18, 0xfa, 0x93, 0xc0, 0xd0, 0x9f, 0x06, 0x86, 0xfe, 0xd3, 0x33, 0x43, 0xbb, 0xd4, 0xbf, 0x29,
	0x45, 0x9f, 0x57, 0xde, 0x60, 0x50, 0xc4, 0xe3, 0x7e, 0xe7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x39, 0xdd, 0xdf, 0x4e, 0x71, 0x09, 0x00, 0x00,
}
