// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: partitionserver.proto

/*
	Package pspb is a generated protocol buffer package.

	It is generated from these files:
		partitionserver.proto

	It has these top-level messages:
		CreateReplicaRequest
		CreateReplicaResponse
*/
package pspb

import (
	"fmt"
	"io"
	"math"

	proto "github.com/golang/protobuf/proto"

	_ "github.com/gogo/protobuf/gogoproto"

	metapb "."

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateReplicaRequest struct {
	Header           *metapb.RequestHeader     `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Partition        *metapb.Partition         `protobuf:"bytes,2,opt,name=partition" json:"partition,omitempty"`
	ReplicaId        uint32                    `protobuf:"varint,3,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	PartitionServers []*metapb.PartitionServer `protobuf:"bytes,4,rep,name=partition_servers,json=partitionServers" json:"partition_servers,omitempty"`
}

func (m *CreateReplicaRequest) Reset()         { *m = CreateReplicaRequest{} }
func (m *CreateReplicaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReplicaRequest) ProtoMessage()    {}
func (*CreateReplicaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorPartitionserver, []int{0}
}

func (m *CreateReplicaRequest) GetHeader() *metapb.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateReplicaRequest) GetPartition() *metapb.Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *CreateReplicaRequest) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *CreateReplicaRequest) GetPartitionServers() []*metapb.PartitionServer {
	if m != nil {
		return m.PartitionServers
	}
	return nil
}

type CreateReplicaResponse struct {
	Header *metapb.ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *CreateReplicaResponse) Reset()         { *m = CreateReplicaResponse{} }
func (m *CreateReplicaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReplicaResponse) ProtoMessage()    {}
func (*CreateReplicaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorPartitionserver, []int{1}
}

func (m *CreateReplicaResponse) GetHeader() *metapb.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateReplicaRequest)(nil), "pspb.CreateReplicaRequest")
	proto.RegisterType((*CreateReplicaResponse)(nil), "pspb.CreateReplicaResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PartitionServerRpc service

type PartitionServerRpcClient interface {
	CreateReplica(ctx context.Context, in *CreateReplicaRequest, opts ...grpc.CallOption) (*CreateReplicaResponse, error)
}

type partitionServerRpcClient struct {
	cc *grpc.ClientConn
}

func NewPartitionServerRpcClient(cc *grpc.ClientConn) PartitionServerRpcClient {
	return &partitionServerRpcClient{cc}
}

func (c *partitionServerRpcClient) CreateReplica(ctx context.Context, in *CreateReplicaRequest, opts ...grpc.CallOption) (*CreateReplicaResponse, error) {
	out := new(CreateReplicaResponse)
	err := grpc.Invoke(ctx, "/pspb.PartitionServerRpc/CreateReplica", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PartitionServerRpc service

type PartitionServerRpcServer interface {
	CreateReplica(context.Context, *CreateReplicaRequest) (*CreateReplicaResponse, error)
}

func RegisterPartitionServerRpcServer(s *grpc.Server, srv PartitionServerRpcServer) {
	s.RegisterService(&_PartitionServerRpc_serviceDesc, srv)
}

func _PartitionServerRpc_CreateReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServerRpcServer).CreateReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pspb.PartitionServerRpc/CreateReplica",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServerRpcServer).CreateReplica(ctx, req.(*CreateReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PartitionServerRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pspb.PartitionServerRpc",
	HandlerType: (*PartitionServerRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReplica",
			Handler:    _PartitionServerRpc_CreateReplica_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partitionserver.proto",
}

func (m *CreateReplicaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateReplicaRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPartitionserver(dAtA, i, uint64(m.Header.Size()))
		n1, err := m.Header.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Partition != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPartitionserver(dAtA, i, uint64(m.Partition.Size()))
		n2, err := m.Partition.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.ReplicaId != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintPartitionserver(dAtA, i, uint64(m.ReplicaId))
	}
	if len(m.PartitionServers) > 0 {
		for _, msg := range m.PartitionServers {
			dAtA[i] = 0x22
			i++
			i = encodeVarintPartitionserver(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *CreateReplicaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateReplicaResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPartitionserver(dAtA, i, uint64(m.Header.Size()))
		n3, err := m.Header.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func encodeVarintPartitionserver(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CreateReplicaRequest) Size() (n int) {
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovPartitionserver(uint64(l))
	}
	if m.Partition != nil {
		l = m.Partition.Size()
		n += 1 + l + sovPartitionserver(uint64(l))
	}
	if m.ReplicaId != 0 {
		n += 1 + sovPartitionserver(uint64(m.ReplicaId))
	}
	if len(m.PartitionServers) > 0 {
		for _, e := range m.PartitionServers {
			l = e.Size()
			n += 1 + l + sovPartitionserver(uint64(l))
		}
	}
	return n
}

func (m *CreateReplicaResponse) Size() (n int) {
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovPartitionserver(uint64(l))
	}
	return n
}

func sovPartitionserver(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPartitionserver(x uint64) (n int) {
	return sovPartitionserver(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreateReplicaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPartitionserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateReplicaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateReplicaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartitionserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPartitionserver
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &metapb.RequestHeader{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Partition", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartitionserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPartitionserver
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Partition == nil {
				m.Partition = &metapb.Partition{}
			}
			if err := m.Partition.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicaId", wireType)
			}
			m.ReplicaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartitionserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReplicaId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartitionServers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartitionserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPartitionserver
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PartitionServers = append(m.PartitionServers, &metapb.PartitionServer{})
			if err := m.PartitionServers[len(m.PartitionServers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPartitionserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPartitionserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateReplicaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPartitionserver
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateReplicaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateReplicaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartitionserver
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPartitionserver
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &metapb.ResponseHeader{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPartitionserver(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPartitionserver
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPartitionserver(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPartitionserver
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPartitionserver
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPartitionserver
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPartitionserver
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPartitionserver
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPartitionserver(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPartitionserver = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPartitionserver   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("partitionserver.proto", fileDescriptorPartitionserver) }

var fileDescriptorPartitionserver = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x48, 0x2c, 0x2a,
	0xc9, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x29, 0x28, 0x2e, 0x48, 0x92, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x0b, 0xe8,
	0x83, 0x58, 0x10, 0x39, 0x29, 0xae, 0xdc, 0xd4, 0x92, 0x44, 0x08, 0x5b, 0xe9, 0x36, 0x23, 0x97,
	0x88, 0x73, 0x51, 0x6a, 0x62, 0x49, 0x6a, 0x50, 0x6a, 0x41, 0x4e, 0x66, 0x72, 0x62, 0x50, 0x6a,
	0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x2e, 0x17, 0x5b, 0x46, 0x6a, 0x62, 0x4a, 0x6a, 0x91, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xa8, 0x1e, 0x48, 0x57, 0x41, 0x92, 0x1e, 0x54, 0x81, 0x07,
	0x58, 0x32, 0x08, 0xaa, 0x48, 0x48, 0x9f, 0x8b, 0x13, 0xee, 0x10, 0x09, 0x26, 0xb0, 0x0e, 0x41,
	0x98, 0x8e, 0x00, 0x98, 0x44, 0x10, 0x42, 0x8d, 0x90, 0x2c, 0x17, 0x57, 0x11, 0xc4, 0xc6, 0xf8,
	0xcc, 0x14, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xde, 0x20, 0x4e, 0xa8, 0x88, 0x67, 0x8a, 0x90, 0x0b,
	0x97, 0x20, 0x5c, 0x6d, 0x3c, 0xc4, 0x67, 0xc5, 0x12, 0x2c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xe2,
	0x18, 0xe6, 0x06, 0x83, 0xe5, 0x83, 0x04, 0x0a, 0x50, 0x05, 0x8a, 0x95, 0xdc, 0xb9, 0x44, 0xd1,
	0x3c, 0x57, 0x5c, 0x00, 0x0a, 0x28, 0x21, 0x3d, 0x34, 0xdf, 0x89, 0x21, 0x7c, 0x07, 0x51, 0x81,
	0xea, 0x3d, 0xa3, 0x04, 0x2e, 0x21, 0x74, 0xdb, 0x0a, 0x92, 0x85, 0xbc, 0xb8, 0x78, 0x51, 0x8c,
	0x17, 0x92, 0xd2, 0x03, 0x05, 0xbb, 0x1e, 0xb6, 0x00, 0x95, 0x92, 0xc6, 0x2a, 0x07, 0xb1, 0x4d,
	0x89, 0xc1, 0x49, 0xe0, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63,
	0x9c, 0xf1, 0x58, 0x8e, 0x21, 0x89, 0x0d, 0x1c, 0x43, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb0, 0x9d, 0x8c, 0x68, 0xe2, 0x01, 0x00, 0x00,
}
