#!/home/admin/yangyang183/software/install/bin/expect -f

set desthost [lindex $argv 0]
set imagename [lindex $argv 1]

spawn scp $imagename admin@$desthost:/home/admin/yangyang183/go_workspace/src/github.com/tiglabs/baudengine/master/cmd
expect "password:" 
send "1qaz@WSXtest\r"
expect eof


#scp master admin@172.22.212.58:/home/admin/yangyang183/go_workspace/src/github.com/tiglabs/baudengine/master/cmd
